from agency_swarm.tools import BaseTool
from pydantic import Field
from datetime import datetime
import json

class GenerateReport(BaseTool):
    """
    Compiles findings from all agents into a structured investigation report
    with executive summary, threat analysis, network insights, and recommendations.
    """
    investigation_title: str = Field(description="Title of the investigation.")
    network_summary: str = Field(
        default="",
        description="Network analysis findings from NetworkAnalystAgent (JSON or text)."
    )
    intel_summary: str = Field(
        default="",
        description="Data intelligence findings from DataIntelAgent (JSON or text)."
    )
    threat_summary: str = Field(
        default="",
        description="Threat scoring findings from ThreatScoringAgent (JSON or text)."
    )
    overall_threat_level: str = Field(
        default="MEDIUM",
        description="Overall threat level: LOW, MEDIUM, HIGH, or CRITICAL."
    )
    recommendations: str = Field(
        default="",
        description="Recommended actions based on investigation findings."
    )

    def run(self):
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        report_id = f"RPT-{datetime.now().strftime('%Y%m%d%H%M%S')}"

        report = f"""
# SENTINEL INVESTIGATION REPORT
**Report ID:** {report_id}
**Generated:** {timestamp}
**Investigation:** {self.investigation_title}
**Overall Threat Level:** {self.overall_threat_level}

---

## Executive Summary
This report consolidates findings from the SENTINEL Criminal Network Analysis System
multi-agent intelligence pipeline. Overall threat classification: **{self.overall_threat_level}**.

---

## Network Analysis
{self.network_summary if self.network_summary else "No network analysis data provided."}

---

## Data Intelligence
{self.intel_summary if self.intel_summary else "No intelligence data provided."}

---

## Threat Assessment
{self.threat_summary if self.threat_summary else "No threat scoring data provided."}

---

## Recommendations
{self.recommendations if self.recommendations else "No specific recommendations provided."}

---

*This report was auto-generated by SENTINEL. Verify all findings with human analysts before operational use.*
"""
        return json.dumps({
            "report_id": report_id,
            "timestamp": timestamp,
            "title": self.investigation_title,
            "overall_threat_level": self.overall_threat_level,
            "report_content": report.strip()
        }, indent=2)
